import express from 'express';
import crypto from 'crypto';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import { readDb, writeDb, id } from './db.js';
import { auth, adminOnly, signUser } from './auth.js';

const app = express();
app.use(cors());
app.use(express.json());
const PORT = process.env.PORT || 4000;

function cleanUser(u){ if(!u) return null; const {passwordHash,...safe}=u; return safe; }
function championship(db,cid){ return db.championships.find(c=>c.id===cid); }
function teamName(db,tid){ return db.teams.find(t=>t.id===tid)?.name || 'Desconhecido'; }
function publicMatch(db,m){ return {...m,homeTeam:db.teams.find(t=>t.id===m.homeTeamId),awayTeam:db.teams.find(t=>t.id===m.awayTeamId)}; }
function standings(db,cid,groupId=null){
  const teams=db.teams.filter(t=>t.championshipId===cid && (!groupId || t.groupId===groupId));
  const rows=new Map(teams.map(t=>[t.id,{teamId:t.id,name:t.name,groupId:t.groupId,played:0,wins:0,draws:0,losses:0,gf:0,ga:0,points:0}]));
  db.matches.filter(m=>m.championshipId===cid && m.status==='confirmed' && (!groupId || m.groupId===groupId)).forEach(m=>{
    const h=rows.get(m.homeTeamId), a=rows.get(m.awayTeamId); if(!h||!a||m.homeScore==null||m.awayScore==null)return;
    h.played++;a.played++;h.gf+=m.homeScore;h.ga+=m.awayScore;a.gf+=m.awayScore;a.ga+=m.homeScore;
    const c=championship(db,cid); const winPts=c?.pointsWin ?? 3, drawPts=c?.pointsDraw ?? 1;
    if(m.homeScore>m.awayScore){h.wins++;h.points+=winPts;a.losses++;} else if(m.homeScore<m.awayScore){a.wins++;a.points+=winPts;h.losses++;} else{h.draws++;a.draws++;h.points+=drawPts;a.points+=drawPts;}
  });
  return [...rows.values()].map(r=>({...r,gd:r.gf-r.ga})).sort((a,b)=>b.points-a.points||b.gd-a.gd||b.gf-a.gf||a.name.localeCompare(b.name)).map((r,i)=>({...r,position:i+1}));
}
function roundRobin(teamIds){ const ids=[...teamIds]; if(ids.length%2)ids.push(null); const n=ids.length,rounds=[]; let arr=[...ids]; for(let r=0;r<n-1;r++){const games=[];for(let i=0;i<n/2;i++){const a=arr[i],b=arr[n-1-i];if(a&&b)games.push([a,b]);}rounds.push(games);arr=[arr[0],arr[n-1],...arr.slice(1,n-1)];}return rounds; }
function ensureFields(c){ if(c.pointsWin==null)c.pointsWin=3;if(c.pointsDraw==null)c.pointsDraw=1;if(!c.status)c.status='registration';return c; }
function updateChampionshipStatus(db,cid){
  const c=championship(db,cid); if(!c)return null; ensureFields(c); const ms=db.matches.filter(m=>m.championshipId===cid);
  if(ms.length && ms.every(m=>m.status==='confirmed')){
    const overall=standings(db,cid); c.status='finished'; c.finishedAt=c.finishedAt||new Date().toISOString();
    c.podium=overall.slice(0,3).map(r=>({position:r.position,teamId:r.teamId,name:r.name,points:r.points,gf:r.gf,ga:r.ga,gd:r.gd}));
    c.celebrationId=c.celebrationId||id('celebration');
  } else if(ms.length && c.status!=='finished') c.status='active'; return c;
}
function notification(db,{type,title,message,championshipId,matchId,createdFor='admin'}){ db.notifications ||= []; db.notifications.unshift({id:id('not'),type,title,message,championshipId,matchId,createdFor,read:false,createdAt:new Date().toISOString()}); }
function validPassword(v){ return typeof v==='string' && v.length>=8 && /[A-Z]/.test(v) && /[a-z]/.test(v) && /\d/.test(v); }
function validUsername(v){ return typeof v==='string' && /^[A-Za-z0-9._-]{4,30}$/.test(v); }
function adminPublic(db){ const a=db.users.find(u=>u.role==='admin'); return {name:a?.displayName||a?.name||'Administrador'}; }
function recoveryKey(){ return crypto.randomBytes(9).toString('base64url').slice(0,12).toUpperCase(); }

app.get('/api/health',(_,res)=>res.json({ok:true,app:'Champions Amigos'}));
app.post('/api/auth/login',async(req,res)=>{const db=readDb(),{username,password}=req.body;const user=db.users.find(u=>u.username.toLowerCase()===String(username||'').toLowerCase());if(!user||!(await bcrypt.compare(String(password||''),user.passwordHash)))return res.status(401).json({error:'Usuário ou senha inválidos.'});res.json({token:signUser(user),user:cleanUser(user)});});
app.get('/api/me',auth,(req,res)=>{const db=readDb();const u=db.users.find(x=>x.id===req.user.id);if(!u)return res.status(401).json({error:'Conta não encontrada.'});res.json(cleanUser(u));});
app.get('/api/admin/public',auth,(req,res)=>res.json(adminPublic(readDb())));
app.post('/api/account/setup',auth,adminOnly,async(req,res)=>{const db=readDb(),u=db.users.find(x=>x.id===req.user.id);const {username,password,displayName}=req.body;if(!u)return res.status(404).json({error:'Conta não encontrada.'});if(!validUsername(username))return res.status(400).json({error:'Usuário deve ter 4 a 30 caracteres e usar apenas letras, números, ponto, hífen ou sublinhado.'});if(!validPassword(password))return res.status(400).json({error:'A senha deve ter pelo menos 8 caracteres, uma letra maiúscula, uma minúscula e um número.'});if(db.users.some(x=>x.id!==u.id&&x.username.toLowerCase()===username.toLowerCase()))return res.status(409).json({error:'Esse usuário já existe.'});u.username=username.trim();u.passwordHash=await bcrypt.hash(password,10);u.displayName=String(displayName||u.name||'Administrador').trim()||'Administrador';u.mustChangeCredentials=false;let newRecoveryKey=null;if(!u.recoveryKeyHash){newRecoveryKey=recoveryKey();u.recoveryKeyHash=await bcrypt.hash(newRecoveryKey,10);}writeDb(db);res.json({token:signUser(u),user:cleanUser(u),recoveryKey:newRecoveryKey});});
app.post('/api/account/credentials',auth,adminOnly,async(req,res)=>{const db=readDb(),u=db.users.find(x=>x.id===req.user.id);const {username,password,displayName}=req.body;if(!u)return res.status(404).json({error:'Conta não encontrada.'});if(username!==undefined&&!validUsername(username))return res.status(400).json({error:'Usuário inválido.'});if(password!==undefined&&!validPassword(password))return res.status(400).json({error:'A nova senha precisa ter 8+ caracteres, maiúscula, minúscula e número.'});if(username&&db.users.some(x=>x.id!==u.id&&x.username.toLowerCase()===username.toLowerCase()))return res.status(409).json({error:'Esse usuário já existe.'});if(username)u.username=username.trim();if(password)u.passwordHash=await bcrypt.hash(password,10);if(displayName!==undefined)u.displayName=String(displayName).trim()||'Administrador';writeDb(db);res.json({token:signUser(u),user:cleanUser(u)});});
app.post('/api/account/recovery-key',auth,adminOnly,async(req,res)=>{const db=readDb(),u=db.users.find(x=>x.id===req.user.id);if(!u)return res.status(404).json({error:'Conta não encontrada.'});const key=recoveryKey();u.recoveryKeyHash=await bcrypt.hash(key,10);writeDb(db);res.json({recoveryKey:key});});
app.put('/api/account/profile',auth,async(req,res)=>{const db=readDb(),u=db.users.find(x=>x.id===req.user.id);if(!u)return res.status(404).json({error:'Conta não encontrada.'});const {username,password,displayName}=req.body;if(username!==undefined){if(!validUsername(username))return res.status(400).json({error:'Usuário inválido.'});if(db.users.some(x=>x.id!==u.id&&x.username.toLowerCase()===String(username).toLowerCase()))return res.status(409).json({error:'Esse usuário já existe.'});u.username=String(username).trim();}if(password!==undefined&&password){if(!validPassword(password))return res.status(400).json({error:'A senha precisa ter 8+ caracteres, maiúscula, minúscula e número.'});u.passwordHash=await bcrypt.hash(password,10);}if(displayName!==undefined)u.displayName=String(displayName).trim()||u.name;writeDb(db);res.json({token:signUser(u),user:cleanUser(u)});});
app.post('/api/auth/forgot-player',async(req,res)=>{const db=readDb(),username=String(req.body.username||'').trim();const u=db.users.find(x=>x.role==='player'&&x.username.toLowerCase()===username.toLowerCase());if(!u)return res.json({ok:true,message:'Se o usuário existir, a solicitação foi registrada.'});notification(db,{type:'password_reset',title:'Recuperação de senha solicitada',message:`${u.name||u.username} solicitou redefinição de senha.`,createdFor:'admin',championshipId:db.teams.find(t=>t.id===u.teamId)?.championshipId||null});writeDb(db);res.json({ok:true,message:'Solicitação enviada ao ADM. Ele poderá redefinir sua senha.'});});
app.post('/api/auth/admin-recover',async(req,res)=>{const db=readDb(),{username,recoveryKey,password}=req.body;const u=db.users.find(x=>x.role==='admin'&&x.username.toLowerCase()===String(username||'').toLowerCase());if(!u||!u.recoveryKeyHash||!(await bcrypt.compare(String(recoveryKey||''),u.recoveryKeyHash)))return res.status(401).json({error:'Usuário ou chave de recuperação inválidos.'});if(!validPassword(password))return res.status(400).json({error:'A nova senha precisa ter 8+ caracteres, maiúscula, minúscula e número.'});u.passwordHash=await bcrypt.hash(password,10);const key=recoveryKey();u.recoveryKeyHash=await bcrypt.hash(key,10);writeDb(db);res.json({token:signUser(u),user:cleanUser(u),recoveryKey:key});});
app.post('/api/admin/players/:uid/reset-password',auth,adminOnly,async(req,res)=>{const db=readDb(),u=db.users.find(x=>x.id===req.params.uid&&x.role==='player');if(!u)return res.status(404).json({error:'Participante não encontrado.'});if(!validPassword(req.body.password))return res.status(400).json({error:'A senha precisa ter 8+ caracteres, maiúscula, minúscula e número.'});u.passwordHash=await bcrypt.hash(req.body.password,10);notification(db,{type:'password_reset_done',title:'Senha redefinida',message:`A senha de ${u.name||u.username} foi redefinida pelo ADM.`,createdFor:'admin',championshipId:db.teams.find(t=>t.id===u.teamId)?.championshipId||null});writeDb(db);res.json({ok:true});});
app.delete('/api/account',auth,(req,res)=>{const db=readDb();const idx=db.users.findIndex(x=>x.id===req.user.id);if(idx<0)return res.status(404).json({error:'Conta não encontrada.'});const u=db.users[idx];if(u.role==='admin'&&db.users.filter(x=>x.role==='admin').length===1&&db.championships.length)return res.status(400).json({error:'Finalize ou transfira os campeonatos antes de excluir o único ADM.'});db.users.splice(idx,1);writeDb(db);res.json({ok:true});});

app.get('/api/celebrations/pending',auth,(req,res)=>{const db=readDb();db.celebrationViews ||= [];const pending=db.championships.filter(c=>c.status==='finished'&&c.celebrationId&&!db.celebrationViews.some(v=>v.userId===req.user.id&&v.celebrationId===c.celebrationId)).map(c=>({id:c.id,celebrationId:c.celebrationId,name:c.name,podium:c.podium||[],finishedAt:c.finishedAt}));res.json(pending);});
app.post('/api/celebrations/:cid/viewed',auth,(req,res)=>{const db=readDb(),c=championship(db,req.params.cid);if(!c?.celebrationId)return res.status(404).json({error:'Cerimônia não encontrada.'});db.celebrationViews ||= [];if(!db.celebrationViews.some(v=>v.userId===req.user.id&&v.celebrationId===c.celebrationId))db.celebrationViews.push({id:id('view'),userId:req.user.id,championshipId:c.id,celebrationId:c.celebrationId,viewedAt:new Date().toISOString()});writeDb(db);res.json({ok:true});});

app.get('/api/championships',auth,(req,res)=>{const db=readDb();res.json(db.championships.map(ensureFields).filter(c=>req.user.role==='admin'||c.status!=='draft'));});
app.post('/api/championships',auth,adminOnly,(req,res)=>{const {name,format='league',groups=1,pointsWin=3,pointsDraw=1}=req.body;if(!name)return res.status(400).json({error:'Nome obrigatório.'});const db=readDb();if(db.championships.some(c=>c.name.trim().toLowerCase()===String(name).trim().toLowerCase()))return res.status(409).json({error:'Já existe um campeonato com esse nome.'});const c={id:id('cmp'),name,format,groups:Number(groups)||1,pointsWin:Number(pointsWin)||3,pointsDraw:Number(pointsDraw)||1,status:'registration',createdAt:new Date().toISOString(),podium:[]};db.championships.push(c);writeDb(db);res.status(201).json(c);});
app.post('/api/championships/:cid/teams',auth,adminOnly,async(req,res)=>{const db=readDb(),c=championship(db,req.params.cid);if(!c)return res.status(404).json({error:'Campeonato não encontrado.'});if(c.status==='finished')return res.status(400).json({error:'Este campeonato já foi concluído.'});const{name,username,password}=req.body;if(!name||!username||!password)return res.status(400).json({error:'Nome, usuário e senha são obrigatórios.'});if(db.users.some(u=>u.username.toLowerCase()===username.toLowerCase()))return res.status(409).json({error:'Esse login/usuário já existe. Escolha outro.'});if(db.teams.some(t=>t.championshipId===c.id&&t.name.trim().toLowerCase()===String(name).trim().toLowerCase()))return res.status(409).json({error:'Já existe um jogador com esse nome nesta liga.'});const team={id:id('team'),championshipId:c.id,name,groupId:null,createdAt:new Date().toISOString()};const user={id:id('usr'),name,username,passwordHash:await bcrypt.hash(password,10),role:'player',teamId:team.id,createdAt:new Date().toISOString()};db.teams.push(team);db.users.push(user);writeDb(db);res.status(201).json({...team,user:cleanUser(user)});});
app.get('/api/championships/:cid/teams',auth,(req,res)=>{const db=readDb();res.json(db.teams.filter(t=>t.championshipId===req.params.cid).map(t=>({...t,userId:db.users.find(u=>u.teamId===t.id)?.id||null,username:db.users.find(u=>u.teamId===t.id)?.username||''})));});
app.delete('/api/championships/:cid',auth,adminOnly,(req,res)=>{const db=readDb(),c=championship(db,req.params.cid);if(!c)return res.status(404).json({error:'Campeonato não encontrado.'});if(c.status!=='finished')return res.status(400).json({error:'Só é possível excluir uma liga já concluída.'});const teamIds=db.teams.filter(t=>t.championshipId===c.id).map(t=>t.id);const matchIds=db.matches.filter(m=>m.championshipId===c.id).map(m=>m.id);db.championships=db.championships.filter(x=>x.id!==c.id);db.teams=db.teams.filter(t=>t.championshipId!==c.id);db.users=db.users.filter(u=>!teamIds.includes(u.teamId));db.matches=db.matches.filter(m=>m.championshipId!==c.id);db.submissions=(db.submissions||[]).filter(s=>s.championshipId!==c.id&&!matchIds.includes(s.matchId));db.notifications=(db.notifications||[]).filter(n=>n.championshipId!==c.id);db.celebrationViews=(db.celebrationViews||[]).filter(v=>v.championshipId!==c.id);writeDb(db);res.json({ok:true,message:'Liga concluída excluída com sucesso.'});});
app.get('/api/championships/:cid/share-link',auth,adminOnly,(req,res)=>{const db=readDb(),c=championship(db,req.params.cid);if(!c)return res.status(404).json({error:'Campeonato não encontrado.'});const base=String(req.headers.origin||'http://localhost:5173').replace(/\/$/,'');res.json({url:`${base}/?liga=${encodeURIComponent(c.id)}`,championshipId:c.id,name:c.name});});
app.post('/api/championships/:cid/groups',auth,adminOnly,(req,res)=>{const db=readDb(),c=championship(db,req.params.cid);if(!c)return res.status(404).json({error:'Campeonato não encontrado.'});if(c.groups!==2)return res.status(400).json({error:'Este campeonato não foi configurado com 2 grupos.'});const teams=db.teams.filter(t=>t.championshipId===c.id);teams.forEach((t,i)=>t.groupId=i%2===0?'A':'B');writeDb(db);res.json(teams);});
app.post('/api/championships/:cid/generate',auth,adminOnly,(req,res)=>{const db=readDb(),c=championship(db,req.params.cid);if(!c)return res.status(404).json({error:'Campeonato não encontrado.'});const teams=db.teams.filter(t=>t.championshipId===c.id);if(teams.length<2)return res.status(400).json({error:'Cadastre pelo menos 2 times.'});if(db.matches.some(m=>m.championshipId===c.id))return res.status(409).json({error:'Confrontos já foram gerados.'});if(c.groups===2&&teams.some(t=>!t.groupId))teams.forEach((t,i)=>t.groupId=i%2===0?'A':'B');let roundNo=1,created=[];const groups=c.groups===2?['A','B']:[null];for(const gid of groups){const gt=teams.filter(t=>t.groupId===gid);const first=roundRobin(gt.map(t=>t.id));const second=first.map(games=>games.map(([a,b])=>[b,a]));[...first,...second].forEach(games=>{for(const[home,away]of games){const m={id:id('mat'),championshipId:c.id,groupId:gid,round:roundNo,homeTeamId:home,awayTeamId:away,homeScore:null,awayScore:null,status:'pending',submissions:{},resultType:null,adminNote:null,createdAt:new Date().toISOString()};db.matches.push(m);created.push(m);}roundNo++;});}c.status='active';writeDb(db);res.json({message:'Confrontos gerados.',matches:created.length,rounds:roundNo-1});});
app.get('/api/championships/:cid/matches',auth,(req,res)=>{const db=readDb();res.json(db.matches.filter(m=>m.championshipId===req.params.cid).map(m=>publicMatch(db,m)));});
app.get('/api/championships/:cid/standings',auth,(req,res)=>{const db=readDb(),c=championship(db,req.params.cid);if(!c)return res.status(404).json({error:'Campeonato não encontrado.'});if(c.groups===2)return res.json({A:standings(db,c.id,'A'),B:standings(db,c.id,'B'),overall:standings(db,c.id),podium:c.podium||[]});res.json({league:standings(db,c.id),podium:c.podium||[]});});
app.get('/api/championships/:cid/overview',auth,(req,res)=>{const db=readDb(),c=championship(db,req.params.cid);if(!c)return res.status(404).json({error:'Campeonato não encontrado.'});updateChampionshipStatus(db,c.id);const ms=db.matches.filter(m=>m.championshipId===c.id),table=standings(db,c.id);const confirmed=ms.filter(m=>m.status==='confirmed').length;const disputed=ms.filter(m=>m.status==='disputed').length;const pending=ms.filter(m=>m.status!=='confirmed'&&m.status!=='disputed').length;const leaders=table.slice(0,3);const relegated=table.slice(Math.max(0,table.length-2));writeDb(db);res.json({championship:c,stats:{matches:ms.length,confirmed,disputed,pending,progress:ms.length?Math.round(confirmed/ms.length*100):0},standings:table,podium:c.podium||[],leaders,relegated,admin:adminPublic(db)});});
app.get('/api/my/matches',auth,(req,res)=>{const db=readDb(),user=db.users.find(u=>u.id===req.user.id);if(!user?.teamId)return res.json([]);res.json(db.matches.filter(m=>m.homeTeamId===user.teamId||m.awayTeamId===user.teamId).map(m=>publicMatch(db,m)));});
app.post('/api/matches/:mid/submit',auth,(req,res)=>{const db=readDb(),m=db.matches.find(x=>x.id===req.params.mid),user=db.users.find(u=>u.id===req.user.id);if(!m||!user?.teamId||(m.homeTeamId!==user.teamId&&m.awayTeamId!==user.teamId))return res.status(403).json({error:'Você não pode lançar este jogo.'});if(m.status==='confirmed'||m.resultType==='wo')return res.status(400).json({error:'Esta partida já está encerrada e não pode ser alterada.'});const hs=Number(req.body.homeScore),as=Number(req.body.awayScore);if(!Number.isInteger(hs)||!Number.isInteger(as)||hs<0||as<0)return res.status(400).json({error:'Placar inválido.'});m.submissions[user.teamId]={homeScore:hs,awayScore:as,at:new Date().toISOString()};const vals=Object.values(m.submissions);if(vals.length>=2){const same=vals.every(v=>v.homeScore===vals[0].homeScore&&v.awayScore===vals[0].awayScore);if(same){m.homeScore=hs;m.awayScore=as;m.status='confirmed';m.resultType='normal';}else{m.status='disputed';notification(db,{type:'dispute',title:'Resultado divergente',message:`${teamName(db,m.homeTeamId)} informou ${vals[0].homeScore} × ${vals[0].awayScore} e ${teamName(db,m.awayTeamId)} informou outro placar.`,championshipId:m.championshipId,matchId:m.id});}}else {m.status='waiting_confirmation';const other=[m.homeTeamId,m.awayTeamId].find(t=>t!==user.teamId);const otherUser=db.users.find(u=>u.teamId===other);if(otherUser)notification(db,{type:'result_waiting',title:'Resultado aguardando confirmação',message:`${teamName(db,user.teamId)} informou ${hs} × ${as}.`,championshipId:m.championshipId,matchId:m.id,createdFor:otherUser.id});}updateChampionshipStatus(db,m.championshipId);writeDb(db);res.json(publicMatch(db,m));});
app.post('/api/matches/:mid/confirm',auth,(req,res)=>{const db=readDb(),m=db.matches.find(x=>x.id===req.params.mid),user=db.users.find(u=>u.id===req.user.id);if(!m||!user?.teamId||(m.homeTeamId!==user.teamId&&m.awayTeamId!==user.teamId))return res.status(403).json({error:'Sem permissão.'});if(m.status==='confirmed')return res.status(400).json({error:'Esta partida já foi confirmada.'});const submitterIds=Object.keys(m.submissions||{});if(submitterIds.length!==1||submitterIds[0]===user.teamId)return res.status(400).json({error:'A confirmação só pode ser feita pelo adversário que ainda não lançou o placar.'});const first=Object.values(m.submissions)[0];if(!first)return res.status(400).json({error:'Nenhum resultado foi lançado.'});m.submissions[user.teamId]={...first,confirmedAt:new Date().toISOString()};m.homeScore=first.homeScore;m.awayScore=first.awayScore;m.status='confirmed';m.resultType='normal';const otherTeam=[m.homeTeamId,m.awayTeamId].find(t=>t!==user.teamId);const otherUser=db.users.find(u=>u.teamId===otherTeam);if(otherUser)notification(db,{type:'result_confirmed',title:'Resultado confirmado',message:`O resultado ${first.homeScore} × ${first.awayScore} foi confirmado.`,championshipId:m.championshipId,matchId:m.id,createdFor:otherUser.id});updateChampionshipStatus(db,m.championshipId);writeDb(db);res.json(publicMatch(db,m));});
app.post('/api/matches/:mid/admin-result',auth,adminOnly,(req,res)=>{const db=readDb(),m=db.matches.find(x=>x.id===req.params.mid);if(!m)return res.status(404).json({error:'Partida não encontrada.'});const hs=Number(req.body.homeScore),as=Number(req.body.awayScore);if(!Number.isInteger(hs)||!Number.isInteger(as)||hs<0||as<0)return res.status(400).json({error:'Placar inválido.'});m.homeScore=hs;m.awayScore=as;m.status='confirmed';m.resultType='admin';m.adminOverride=true;m.adminNote=req.body.note||null;[m.homeTeamId,m.awayTeamId].forEach(tid=>{const pu=db.users.find(u=>u.teamId===tid);if(pu)notification(db,{type:'admin_correction',title:'Resultado corrigido pelo ADM',message:`Placar oficial: ${hs} × ${as}.`,championshipId:m.championshipId,matchId:m.id,createdFor:pu.id});});updateChampionshipStatus(db,m.championshipId);writeDb(db);res.json(publicMatch(db,m));});
app.post('/api/matches/:mid/wo',auth,adminOnly,(req,res)=>{const db=readDb(),m=db.matches.find(x=>x.id===req.params.mid);if(!m)return res.status(404).json({error:'Partida não encontrada.'});if(m.status==='confirmed')return res.status(400).json({error:'Esta partida já está encerrada.'});const loser=req.body.loserTeamId,winner=loser===m.homeTeamId?m.awayTeamId:m.homeTeamId;if(loser!==m.homeTeamId&&loser!==m.awayTeamId)return res.status(400).json({error:'Jogador perdedor inválido.'});const goals=Math.max(1,Number(req.body.goals)||3);m.homeScore=winner===m.homeTeamId?goals:0;m.awayScore=winner===m.awayTeamId?goals:0;m.status='confirmed';m.resultType='wo';m.adminNote=req.body.note||'W.O. aplicado pelo administrador';updateChampionshipStatus(db,m.championshipId);writeDb(db);res.json(publicMatch(db,m));});
app.get('/api/my/notifications',auth,(req,res)=>{const db=readDb();db.notifications ||= [];res.json(db.notifications.filter(n=>n.createdFor===req.user.id).slice(0,50));});
app.get('/api/notifications',auth,adminOnly,(req,res)=>{const db=readDb();db.notifications ||= [];res.json(db.notifications.filter(n=>n.createdFor==='admin').slice(0,50));});
app.post('/api/notifications/:nid/read',auth,adminOnly,(req,res)=>{const db=readDb();const n=(db.notifications||[]).find(x=>x.id===req.params.nid);if(!n)return res.status(404).json({error:'Notificação não encontrada.'});n.read=true;writeDb(db);res.json(n);});
app.get('/api/dashboard',auth,adminOnly,(req,res)=>{const db=readDb();const matches=db.matches;res.json({championships:db.championships.length,teams:db.teams.length,totalMatches:matches.length,confirmed:matches.filter(m=>m.status==='confirmed').length,pending:matches.filter(m=>m.status==='pending'||m.status==='waiting_confirmation').length,disputed:matches.filter(m=>m.status==='disputed').length,notifications:(db.notifications||[]).filter(n=>n.createdFor==='admin'&&!n.read).length,finished:db.championships.filter(c=>c.status==='finished').length});});
app.listen(PORT,()=>console.log(`Champions Amigos API: http://localhost:${PORT}`));
